# test
server:
  port: 8100
  #servlet:
  #  context-path: /api

spring:
  application:
    name: apigateway-service
  profiles:
    active: local
  cloud:
    gateway:
      default-filters:
        - name : GlobalFilter
          args :
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id : mapservice-rest
          uri: lb://MAPSERVICE-REST
          predicates:
            - Path=/map/**
          filters:
            #              - AddRequestHeader=first-request, first-request-header2
            #              - AddResponseHeader=first-response, first-response-header2
            - name : CustomFilter
        - id: lb://MY-SECOND-SERVICE
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
          filters:
            #              - AddRequestHeader=second-request, second-request-header2
            #              - AddResponseHeader=second-response, second-response-header2
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, there.
                preLogger: true
                postLogger: true