# test
server:
  port: 8100
  #servlet:
  #  context-path: /api

spring:
  application:
    name: apigateway-service
#  profiles:
#    active: local
  cloud:
    cloud:
      loadbalancer:
        enabled: true
    gateway:
      default-filters:
        - name : GlobalFilter
          args :
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id : mapservice-rest
          uri: lb://MAPSERVICE-REST
          predicates:
            - Path=/map/**
          filters:
            #              - AddRequestHeader=first-request, first-request-header2
            #              - AddResponseHeader=first-response, first-response-header2
            - name : CustomFilter
        - id: sj-lab-scheduler
          uri: lb://SJ-LAB-SCHEDULER
          predicates:
            - Path=/scheduler/**
          filters:
            #              - AddRequestHeader=first-request, first-request-header2
            #              - AddResponseHeader=first-response, first-response-header2
            - name: CustomFilter
#        - id: lb://MY-SECOND-SERVICE
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/scheduler/**
#          filters:
#            #              - AddRequestHeader=second-request, second-request-header2
#            #              - AddResponseHeader=second-response, second-response-header2
#            - name: CustomFilter
#            - name: LoggingFilter
#              args:
#                baseMessage: Hi, there.
#                preLogger: true
#                postLogger: true
      globalcors:
        add-to-simple-url-handler-mapping: true   # OPTIONS 처리 보장
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4000
              - https://sj-lab.co.kr
              - https://www.sj-lab.co.kr
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: [ "*" ]
            exposedHeaders:
              - Content-Length
              - Content-Range
            allowCredentials: true
            maxAge: 3600
        # (선택) 중복 헤더 제거 - 백엔드도 CORS 넣는 경우 충돌 방지
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_UNIQUE