apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: sj-lab
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30089
  type: NodePort
